Mongo:
  Hosts:
    - 127.0.0.1:27017
  Database: login_register
  User: wwy
  Password: "123456"
  AuthSource: admin
  AuthMechanism: SCRAM-SHA-256
JWT:
  SecretKey: "sadasdsadfsdfwdfdafd"  # 替换为实际密钥
  ExpireHours: 24